version: 2.1

orbs:
  codecov: codecov/codecov@3

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout

      - run:
          name: Installer Maven
          command: sudo apt-get update && sudo apt-get install -y maven

      - run:
          name: Configurer Maven
          command: mvn -B -f pom.xml clean install

      - run:
          name: Lancer les tests unitaires avec JaCoCo et générer le rapport
          command: mvn clean test -X

      - run:
          name: Vérifier la présence du rapport JaCoCo
          command: ls -l target/site/jacoco/

      - run:
          name: Générer le rapport HTML Checkstyle
          command: mvn checkstyle:checkstyle

      - run:
          name: Upload du rapport de couverture vers Codecov
          command: |
            curl -s https://codecov.io/bash | bash -s
          env:
            CODECOV_TOKEN: $CODECOV_TOKEN
      - codecov/upload

      - run:
          name: Générer la Javadoc
          command: mvn javadoc:javadoc

      - run:
          name: Préparer les fichiers pour GitHub Pages
          command: |
            mkdir -p gh-pages
            cp -R target/reports/apidocs/* gh-pages/
            cd gh-pages
            git init
            git remote add origin https://$GH_TOKEN@github.com/FrancoisDemogue/ceri-m1-techniques-de-test.git
            git fetch origin gh-pages || echo "La branche gh-pages n'existe pas encore"
            git checkout -B gh-pages
            # Copier la nouvelle Javadoc
            cp -R ../gh-pages/* .
            # Ajouter et valider les changements
            git add .
            git commit -m "Mise à jour de la Javadoc [skip ci]" || echo "Aucun changement détecté"
            git push -u origin gh-pages


workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
