version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout

      - run:
          name: Configurer Maven
          command: mvn -B -f pom.xml clean install

      - run:
          name: Lancer les tests unitaires
          command: mvn test

  upload-to-codecov:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - codecov/upload

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - upload-to-codecov:
          requires:
            - build

orbs:
  codecov: codecov/codecov@5
