version: 2.1

orbs:
  codecov: codecov/codecov@3

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout

      - run:
          name: Configurer Maven
          command: mvn -B -f pom.xml clean install

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Lancer les tests unitaires avec JaCoCo
          command: mvn test

      - run:
          name: Générer le rapport de couverture JaCoCo
          command: mvn jacoco:report

      - run:
          name: Générer le rapport HTML Checkstyle
          command: mvn checkstyle:checkstyle

      - run:
          name: Upload du rapport de couverture vers Codecov
          command: |
            curl -s https://codecov.io/bash | bash -s -- -f target/site/jacoco/jacoco.xml
          env:
            CODECOV_TOKEN: $CODECOV_TOKEN


workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
