version: 2.1
orbs:
  codecov: codecov/codecov@5
  
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout

      - run:
          name: Configurer Maven
          command: mvn -B -f pom.xml clean install

      - run:
          name: Lancer les tests unitaires
          command: mvn test
      
      - run:
          name: Install dependencies
          command: npm install
          
      - run:
          name: Run tests and collect coverage
          command: npm run test
          
      - codecov/upload


workflow:
  version: 2.1
  build-test:
    jobs:
      - build


