version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk  # Utilisation de Java 8, peut être remplacé par 11 ou 17 si besoin
    steps:
      - checkout  # Récupère le code source

      - run:
          name: Configurer Maven
          command: mvn -B -f pom.xml clean install  # Nettoie le projet et installe les dépendances Maven

      - run:
          name: Lancer les tests unitaires
          command: mvn test  # Exécute les tests unitaires avec Maven

  upload-to-codecov:
    docker:
      - image: circleci/python:3.8  # Utilisation d'une image docker avec Python (si nécessaire pour le plugin Codecov)
    steps:
      - checkout  # Récupère le code source
      - codecov/upload  # Étape de l'orb Codecov pour télécharger les résultats

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master  # Filtrer pour que le job soit exécuté uniquement sur la branche master
      - upload-to-codecov:
          requires:
            - build  # S'assure que l'upload est effectué après le job de build

orbs:
  codecov: codecov/codecov@5
