version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk  # Utilisation de Java 8, peut être remplacé par 11 ou 17 si besoin
    steps:
      - checkout  # Récupère le code source

      - run:
          name: Configurer Maven
          command: mvn -B -f pom.xml clean install  # Nettoie le projet et installe les dépendances Maven

      - run:
          name: Lancer les tests unitaires
          command: mvn test  # Exécute les tests unitaires avec Maven

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master  # Filtrer pour que le job soit exécuté uniquement sur la branche master
orbs:
  codecov: codecov/codecov@5
workflows:
  upload-to-codecov:
    jobs:
      - checkout 
      - codecov/upload
