version: 2.1

orbs:
  codecov: codecov/codecov@3

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout

      - run:
          name: Configurer Maven
          command: mvn -B -f pom.xml clean install

      - run:
          name: Build docs
          command: cd docs/ && make html
      - persist_to_workspace:
          root: docs/_build
          paths: html

      - run:
          name: Lancer les tests unitaires avec JaCoCo et générer le rapport
          command: mvn clean test -X

      - run:
          name: Vérifier la présence du rapport JaCoCo
          command: ls -l target/site/jacoco/

      - run:
          name: Générer le rapport HTML Checkstyle
          command: mvn checkstyle:checkstyle

      - run:
          name: Upload du rapport de couverture vers Codecov
          command: |
            curl -s https://codecov.io/bash | bash -s
          env:
            CODECOV_TOKEN: $CODECOV_TOKEN
      - codecov/upload


workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
